name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm packages
        run: npm ci

      - name: Build Storybook
        run: npm run build-storybook

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist/storybook/ui
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
